/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pp.muza.monopoly;

import java.util.ArrayList;
import java.util.List;

import org.apache.commons.cli.CommandLine;
import org.apache.commons.cli.CommandLineParser;
import org.apache.commons.cli.DefaultParser;
import org.apache.commons.cli.HelpFormatter;
import org.apache.commons.cli.Option;
import org.apache.commons.cli.Options;
import org.apache.commons.cli.ParseException;

import pp.muza.monopoly.model.game.Bank;
import pp.muza.monopoly.model.game.Board;
import pp.muza.monopoly.model.game.Game;
import pp.muza.monopoly.model.lands.Land;
import pp.muza.monopoly.model.player.Player;
import pp.muza.monopoly.model.lands.BoardHelper;
import pp.muza.monopoly.model.player.strategy.DefaultPlayer;

/**
 * This is a simple Monopoly game.
 *
 * @author Muza
 */
public class App {

    public static final int DEFAULT_PLAYERS = 2;

    static final String OPT_PLAYERS = "players";

    private static int players = DEFAULT_PLAYERS;

    public String getGreeting() {
        return "This is a game of Monopoly!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        // check command line argument -p for number of players

        Options options = new Options();
        options.addOption(Option.builder("p").longOpt(OPT_PLAYERS).hasArg().desc("define number of players")
                .type(Integer.class).build());

        CommandLineParser parser = new DefaultParser();
        HelpFormatter helpFormatter = new HelpFormatter();
        try {
            CommandLine cmd = parser.parse(options, args);
            if (cmd.hasOption(OPT_PLAYERS)) {
                players = Integer.parseInt(cmd.getOptionValue("players"));
                if (players < 1 || players > 4) {
                    throw new IllegalArgumentException("Number of players must be between 1 and 4");
                }
                System.out.println("Number of players: " + players);
            }
        } catch (ParseException e) {
            System.out.println(e.getMessage());
            helpFormatter.printHelp("java -jar <jar-file>", options);
            System.exit(1);
        }
        game();
    }

    static void game() {
        List<Player> p = new ArrayList<>();
        for (int i = 0; i < players; i++) {
            p.add(new DefaultPlayer("Player " + (i + 1)));
        }

        Board<Land> board = BoardHelper.defaultBoard();
        Bank bank = new Bank();
        Game game = new Game(board, bank, p);
        game.gameLoop();
    }
}
