/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pp.muza.monopoly.app;

import com.google.common.collect.ImmutableList;
import org.apache.commons.cli.*;
import pp.muza.monopoly.model.Player;
import pp.muza.monopoly.model.bank.BankImpl;
import pp.muza.monopoly.model.game.GameImpl;
import pp.muza.monopoly.strategy.DefaultStrategy;
import pp.muza.monopoly.model.ChancePile;
import pp.muza.monopoly.model.BoardLayout;

import java.util.List;
import java.util.stream.Collectors;
import java.util.stream.IntStream;

/**
 * This is a simple Monopoly game simulator
 */
public class App {

    public static final int DEFAULT_PLAYERS = 2;
    public static final int MAX_PLAYERS = 4;
    public static final int MIN_PLAYERS = 2;

    static final String OPT_PLAYERS = "players";

    private static int playersNumber = DEFAULT_PLAYERS;

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        Options options = new Options();
        options.addOption(Option.builder("p").longOpt(OPT_PLAYERS).hasArg().desc("define number of players")
                .type(Integer.class).build());

        CommandLineParser parser = new DefaultParser();
        HelpFormatter helpFormatter = new HelpFormatter();
        try {
            CommandLine cmd = parser.parse(options, args);
            if (cmd.hasOption(OPT_PLAYERS)) {
                playersNumber = Integer.parseInt(cmd.getOptionValue("players"));
                if (playersNumber < MIN_PLAYERS || playersNumber > MAX_PLAYERS) {
                    throw new IllegalArgumentException(String.format("Number of players must be between %s and %s", MIN_PLAYERS, MAX_PLAYERS));
                }
                System.out.println("Number of players: " + playersNumber);
            }
        } catch (ParseException e) {
            System.out.println(e.getMessage());
            helpFormatter.printHelp("java -jar <jar-file>", options);
            System.exit(1);
        }
        game();
    }

    static void game() {
        List<Player> players = IntStream.range(0, playersNumber).mapToObj(i -> new Player("@Player" + (i + 1)))
                .collect(Collectors.toList());
        GameImpl game = new GameImpl(BoardLayout.defaultBoard(), players, ChancePile.defaultPile(),
                ImmutableList.of(DefaultStrategy.getInstance()), new BankImpl());
        game.gameLoop();
    }


    public String getGreeting() {
        return "This is a game of Monopoly!";
    }
}
