/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pp.muza.monopoly.app;

import java.util.List;
import java.util.stream.Collectors;
import java.util.stream.IntStream;

import org.apache.commons.cli.CommandLine;
import org.apache.commons.cli.CommandLineParser;
import org.apache.commons.cli.DefaultParser;
import org.apache.commons.cli.HelpFormatter;
import org.apache.commons.cli.Option;
import org.apache.commons.cli.Options;
import org.apache.commons.cli.ParseException;

import pp.muza.monopoly.errors.GameException;
import pp.muza.monopoly.errors.TurnException;
import pp.muza.monopoly.model.*;
import pp.muza.monopoly.model.bank.BankImpl;
import pp.muza.monopoly.model.game.BaseGame;
import pp.muza.monopoly.model.game.GameImpl;
import pp.muza.monopoly.strategy.DefaultStrategy;

/**
 * This is a simple Game game simulator
 */
public class App {

    public static final int DEFAULT_PLAYERS = 2;
    public static final int MAX_PLAYERS = 4;
    public static final int MIN_PLAYERS = 2;

    static final String OPT_PLAYERS = "players";

    private static int playerNumbers = DEFAULT_PLAYERS;

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        Options options = new Options();
        options.addOption(Option.builder("p").longOpt(OPT_PLAYERS).hasArg().desc("define number of players")
                .type(Integer.class).build());

        CommandLineParser parser = new DefaultParser();
        HelpFormatter helpFormatter = new HelpFormatter();
        try {
            CommandLine cmd = parser.parse(options, args);
            if (cmd.hasOption(OPT_PLAYERS)) {
                playerNumbers = Integer.parseInt(cmd.getOptionValue("players"));
                if (playerNumbers < MIN_PLAYERS || playerNumbers > MAX_PLAYERS) {
                    throw new IllegalArgumentException(String.format("Number of players must be between %s and %s", MIN_PLAYERS, MAX_PLAYERS));
                }
                System.out.println("Number of players: " + playerNumbers);
            }
        } catch (ParseException e) {
            System.out.println(e.getMessage());
            helpFormatter.printHelp("java -jar <jar-file>", options);
            System.exit(1);
        }

        try {
            game();
        } catch (TurnException | GameException e) {
            throw new RuntimeException(e);
        }

    }

    static void game() throws TurnException, GameException {
        List<Player> players = IntStream.range(0, playerNumbers).mapToObj(i -> new Player("@Player" + (i + 1)))
                .collect(Collectors.toList());
        PlayGame game = new GameImpl(new BankImpl(), BoardLayout.defaultBoard(), ChancePile.defaultPile(), players);
        while (game.isGameInProgress()) {
            PlayTurn turn = game.getTurn();
            ActionCard card = DefaultStrategy.getInstance().playTurn(turn.getTurnInfo());
            turn.playCard(card);
        }
    }


    public String getGreeting() {
        return "This is a game of Game!";
    }
}
